version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: cargo
  directory: /jsonnet-sys
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
