language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - cat /etc/os-release
  - ${CXX:-c++} --version
script:
  - cargo build --verbose
  - cargo test --verbose --manifest-path=jsonnet-sys/Cargo.toml
  - cargo test --verbose
  - cargo doc --no-deps
notifications:
  email:
    on_success: never
addons:
  apt:
    packages:
      - g++-4.9
